version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
   #   - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'Europe/Vienna'
      WEBPASSWORD: ${WEBPASSWORD}
      PIHOLE_DNS_: '1.1.1.1;8.8.8.8'
      WEBTHEME: 'default-darker'
    # Volumes store your data between container upgrades
    volumes:
      - '/portainer/pihole-docker/volumes/etc-dnsmasq.d:/etc/dnsmasq.d'
      - '/portainer/pihole-docker/volumes/etc-pihole:/etc/pihole'
      - '/portainer/pihole-docker/custom.list:/etc/pihole/custom.list'
    restart: unless-stopped
